# Generated by Django 2.2.4 on 2019-08-26 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.SmallIntegerField(choices=[(0, 'Male'), (1, 'Femail'), (2, 'Not to disclose')], default=0),
            preserve_default=False,
        ),
    ]
